# comments
#Target : dependency
#<TAB>Command

PROJECT_NAME = finalcode.exe
SCR = final.c add.c delete.c modify.c indivisual.c printchar.c title.c

$(PROJECT_NAME): $(SRC)
     gcc $(SCR) -o finalcode.exe

run:$(PROJECT_NAME)
    $(PROJECT_NAME)