name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install math library
      run:  sudo apt-get install -y libmath-libm-perl
 

    - name: make all
      run:  make all 
