name: CodeQuality Dynamic Code Analysis Valgrind
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: make -C implementation/main.c
    - name: Valgrid
      run: valgrind ./implementation/build/main.c
